### PR TITLE
Improve Darwin support

### LINKED ISSUE #7: Tutorials do not work on macOS
Running `configure.sh` in both tutorials on macOS crashes with the error
```
readlink: illegal option -- e
usage: readlink [-fn] [file ...]
```

System information:  
`Darwin Seppes-MacBook-Pro.local 23.3.0 Darwin Kernel Version 23.3.0: Wed Dec 20 21:30:59 PST 2023; root:xnu-10002.81.5~7/RELEASE_ARM64_T6030 arm64`

Python version:  
`Python 3.12.2`

This is due to the behavior of `readlink` being different on macOS.
(readline is called with the option -e in [add_paths_venv.sh](https://github.com/open-s4c/benchkit/blob/0d4ac8ea9a80aa08a7d11f9cf17123d8c79609e4/scripts/add_paths_venv.sh#L14C18-L14C29), which macOS' version of readlink does not support.)

### PR DESCRIPTION
**Pull request by seppewyns**
This PR aims to improve support for Darwin operating systems (macOS).
Although this does not completely add support for macOS *yet*, it fixes some bugs that occur when running the tutorials on macOS or Windows.

- Fixes #7 by replacing the `add_paths_venv.sh` shell script by a `add_paths_venv.py` python script which does not use `readlink` or `realpath` directly.
- Fixes an error that occurs when `get_nb_cpus_total` or `get_nb_cpus_isolated` is called on macOS or Windows.

Note: running the tutorials on macOS still throws an exception due to a [check](https://github.com/open-s4c/benchkit/blob/17451b963e5dff0f57560fc7cdd3e6e6fc3287e6/benchkit/utils/system.py#L37-L38) that validates whether the operating system is supported. Adding Darwin to this check prevents the error. (I didn't add it in this PR to because macOS isn't officially supported yet.)

### CODE REVIEW

**Review by apaolillo — DISMISSED** [review]
Thanks a lot! I like the idea of converting the add_paths_venv into python, because readlink was causing a lot of issues to other Mac users. I'll apply small fixes on top of your patch myself.

**Comment by apaolillo** [comment]
@seppewyns hello Seppe! Could you please rebase your PR against main? As is, the merge is blocked by à conflict.

**Comment by seppewyns** [comment]
@apaolillo I just pushed the rebased commits. I also added the ability to specify a venv path as introduced in d655887.

**Review by apaolillo — APPROVED** [review]
Thanks a lot Seppe! Merging now.

**Pull request merged**
