### PR TITLE
added an example doing a considerable amount of work in a large range of implementations

### PR DESCRIPTION
**Pull request by aaronbog**
added an example where we benchmark multiple implementations over multiple campaigns

work still to be done:

- the sequential campaign does not work since it still needs expansion and was written early on
- a small test suite that guarantees the correct functioning of all implementations
- tests that make use of perf

notes:

- this requires the shell improvements to remove the perf data

### CODE REVIEW

**Comment by apaolillo** [comment]
@aaronbog Hello Aaron! Thanks for the pull request. May I ask you to split the contribution to benchkit core itself in a separate pull request? These changes should be isolated to minimize their potential impact. For your benchmark project, could you provide a more accurate description? Like the video games on which it was based, and giving a bit of context. Thanks in advance!

**Comment by aaronbog** [comment]
@apaolillo  I will make the other changes into their own pull request.
What is the best way for me to indicate that this pull request will be dependent on two other pull requests?

**Comment by apaolillo** [comment]
> What is the best way for me to indicate that this pull request will be dependent on two other pull requests?

You can add a comment just like that, mentioning the other PRs that must be merged first (e.g. #30 )
You can also put the PRs that cannot be merged as "draft" temporarily.

**Comment by apaolillo** [comment]
(sorry for closing, it was a misclick)

**Comment by apaolillo** [comment]
@aaronbog same for this one. I understood it is blocked by other features.

**Pull request closed without merging**
