### PR TITLE
Adding a post_run_hook to TraceCmd

### PR DESCRIPTION
**Pull request by matsvanmolle**
Adding a post_run_hook to TraceCmd.

This post_run_hook can be used to do processing of the data generated by trace-cmd.

### CODE REVIEW

**Comment by matsvanmolle** [comment]
I'm currently encountering a bug.
The `generate-graph.out` file is empty. I'm certain that the hook runs, when I provide it with a non-existing `.dat` file I get output in the `.err` file telling me the file does not exist.

**Comment by apaolillo** [comment]
@matsvanmolle if you think it is now ready, you can remove the "draft" status from the PR

**Comment by matsvanmolle** [comment]
> @matsvanmolle if you think it is now ready, you can remove the "draft" status from the PR

@apaolillo Should the graph drawer also be included in the post_run_hook?

**Comment by apaolillo** [comment]
> @apaolillo Should the graph drawer also be included in the post_run_hook?

@matsvanmolle You can if it is ready but we can also merge piece by piece as this PR is quite self-contained.

**Review by apaolillo — APPROVED** [review]

**Pull request merged**
